<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class RegisterRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            "name" => ["required", "string"],
            "phoneNumber" => ["required", "string", "unique:users,phoneNumber"],
            "role" => ['required'],
            "password" => ["required", "confirmed"]
        ];
    }

    public function messages()
    {
        return [
            'name' => [
                'required' => 'Поле имя обязательно к заполнению',
                 'string' => 'поле должен быть строкой'
            ],
            'phoneNumber' => 'Поле номер телефона обязательно к заполнению',
            'role' => 'выберите типа вашего аккаунта',
            'password' => [
                'required' => 'Пароль обязательно к заполнению',
                'confirmed' => 'Введенный пароль и его подтверждение неидентичны',
            ]

        ];
    }

    public function attributes()
    {
        return parent::attributes(); // TODO: Change the autogenerated stub
    }
}
